modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://frozenblock.net"
logoFile = "assets/${mod_id}/icon.png"
credits = "${credits}"
authors = "${mod_author}"
description = "${mod_description}"

[mods.frozenlib.entrypoints]
main = ["net.frozenblock.ml_template.neoforge.FrozenBlockMLTemplateNeoForge"]
client = ["net.frozenblock.ml_template.neoforge.FrozenBlockMLTemplateNeoForgeClient"]
server = ["net.frozenblock.ml_template.neoforge.FrozenBlockMLTemplateNeoForge"]

[[mixins]]
config = "mixin/${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[["dependencies.${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[["dependencies.${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range_neoforge}"
ordering = "NONE"
side = "BOTH"
